services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      retries: 5
      start_period: 30s
    ports:
      - '5432:5432'
  neonDbProxy:
    image: ghcr.io/timowilhelm/local-neon-http-proxy:main
    environment:
      PG_CONNECTION_STRING: postgres://postgres:postgres@db:5432/postgres
    ports:
      - '4444:4444'
    depends_on:
      db:
        condition: service_healthy
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    pull_policy: build
    command: ['bun', 'dev:docker', '-v']
    extra_hosts:
      - 'db.localtest.me:host-gateway'
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api
    ports:
      - '5173:5173'
    command: ['bun', 'dev', '--host=0.0.0.0']

volumes:
  db_data:
    driver: local
