env:
  browser: false
  node: true
  es2021: true
extends:
  - standard-with-typescript
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
settings:
  react: "detect"
plugins:
  - '@stylistic'
rules:
  semi: "off"
  yoda: "off"
  "@typescript-eslint/semi": [2, "always"]
  no-useless-escape: "off"
  comma-dangle: "off"
  "@typescript-eslint/comma-dangle": "off"
  "@stylistic/comma-dangle":
    - "error"
    - arrays: "always-multiline"
      objects: "always-multiline"
      functions: "always-multiline"
      imports: "always-multiline"
      generics: "only-multiline"
  brace-style: "off"
  "@typescript-eslint/brace-style":
    - "error"
    - "stroustrup"
  "@typescript-eslint/strict-boolean-expressions":
    - "error"
    - "allowString": false
  "@typescript-eslint/quotes": "off"
  "@typescript-eslint/no-misused-promises": "off"
  no-trailing-spaces: "off"
  no-useless-return: "off"
  "@typescript-eslint/naming-convention": "off"
  "@typescript-eslint/consistent-type-imports": "off"
  "@typescript-eslint/no-confusing-void-expression":
    - "error"
    - "ignoreArrowShorthand": true
  "@typescript-eslint/consistent-type-definitions":
    - "error"
    - "type"
  space-before-function-paren: "off"
  "@typescript-eslint/space-before-function-paren":
    - "error"
    - anonymous: "always"
      named: "never"
      asyncArrow: "always"
  "@typescript-eslint/member-delimiter-style":
    - "error"
    - multiline:
        delimiter: semi
        requireLast: true
      singleline:
        delimiter: comma
        requireLast: true
  "@typescript-eslint/explicit-function-return-type": "off"
  no-multiple-empty-lines: "off"
  eol-last: "off"
  "@typescript-eslint/array-type":
    - "error"
    - "default": "generic"
  "@typescript-eslint/promise-function-async":
    - "error"
    - checkArrowFunctions: false
  "@stylistic/object-property-newline":
    - "error"
    - allowAllPropertiesOnSameLine: true
